apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: basic-auth
    namespace: networking
stringData:
    users: ENC[AES256_GCM,data:4L+18i29BZrHs0y2Gmnzqmr2D2Z5UQN9aUcMHj/pnGHoXp28VCGG5+OPAw==,iv:cDbgRFjnuqUIkfA+pGNNd983/huORMgPaQ9IvOOgiiY=,tag:xNNVfpok1NqZTF/+zUtsdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-16T16:10:06Z"
    mac: ENC[AES256_GCM,data:+UFNMoL2PdB5FUAweTPxp2E2Z6DQJDVZoKI/QIkMUs5tDplveGWugb3StLSyvVbux52rfH8EZYfpk801zXOT10/B6FF4cPKH7SDt9sJbO5F3y8NPyPMaX9qgzNdnvaASUSz5fNpnWu2+uH+p8qHqVie9Iudl/YYXt01cOvlOw3U=,iv:2rLr31sYzCCN6/5PF0uFp1uxtQMUTp9+5CvN4IWSfSY=,tag:mYh3MOyCgTK3r76M1Faqvw==,type:str]
    pgp:
        - created_at: "2021-09-13T18:31:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA/VTXGv6F5F7ARAAZdIn9lXFPZOYS9eEfeMh9OYjjjD6tlsyl6/i56E71lfl
            BOzHOMe2I1kw1ODud0pQ+3kbjmYrL6Sw2ACYmCRPqxCLvSgFceha3hIRBsm13I42
            BPsr9HGtlwk2ndO3eHGf0n/uy5c49kcYpt2jVTIMxh+oruiKkr67zXEaz5M72sXL
            ZH5Wjzz7dUoi9IEC3UXjtifsvaBK9qQZymG2bEBlxOFUbh7hOfkyvStsVeuCApip
            4O0+oA0S+PXHSloQUtFyo5IATl0Ht0EmmPx03jPLmQC+zNVn6T6MnKq+OW361UJR
            ad/50f473deEfgAI6XJJLh7e5eomyn56I8L2eaW06s9djJM259HncOTXT3tMqUET
            f1O0KFRiFIanYrTVMctTJRDKTu40jupdNBP0Vn+6S36X1ss/wv6GqZitjFNYbFhH
            qCbafOkoCOkG6BaQXgmmfQJK8v5C5vkjNNznUuCFLp/r0Z5+airHq6ltZmcoaRb3
            u9DCym7QgB3MLd3mgeH9pWGZ2JGeONGsvThFI/LqUYLPSqn5bHVUI0o72C3Ni03T
            9eP7ZG8m1tOB83M2X3rkEDavvFq45thA246UnMlXsG5F6vWxg/cfY1MXtFDtNDyw
            Rt8dWQh+DZq5ChzPJcU6zX8+8MVq1GYlbKrcC+i25vR8OD38jIS9cW4vxTYu4YDS
            5gFiavxRqrTUfrroqgFWBg1phzJMNY7lOzvD0PGlAFVx2mF/tLI6qI9Hk6Z4bj55
            ArxNMOsBwfyvEi64Ys8gAo7k4XhLBCEI+LgFu5nkpKdu9OKh5eiZAA==
            =l88e
            -----END PGP MESSAGE-----
          fp: EF57DFB4F82884FC2F1387331CC7DF8BAC25CF9E
        - created_at: "2021-09-13T18:31:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA6gu/1ZdgRhxARAAFVPGww5e0+s4Lliz7Iwr95LzwONfpfT9mQIPFElZaNsg
            ElTvsxdM+AtiML68vD8xooAQ/iYmRUU3IAnX6aZSyDY+h1iy/wfyGPLfGYG6c2rU
            rrUiFQIKaIDEjDt04aYJFkDARRa/9lbYfcUhp5cNhmVy+dhdn3MifwG3Fvfra9mV
            rw1q2Y7aB2zQIv+a34x8NzcyyWWcDKzPeG6INTjqFYLSwZcpHW5mjZ/EjvZI0GJC
            RK/GytntaTZZJSHicQMVGRq8WWE3n1JXVn+NXGIPqM0FO+RQbjJn8xptMAJGjzyO
            uBZXhqCxq2VCiK+HFxbXDGyFzUfW34WcTnR8tfIHwvtEA2Iu+npQ7iRODlsXnMts
            xQx46TSR//HPSTtsq20WX+9aSHXp5s7rnkKkwL67l/fyjKgCMSpcx5gcnKhbmzbI
            zVvD334iFosMLz59cBixvTG2g/U830K4bds5eJ8eOJXE7tsEmr7W0EWpKfJZP8F3
            PUk6L06cNtyDtMC3wItyeImypsxLcoswh/xMxB8Woo5Ti3rsu4Ar8HeaWv3RivFc
            kA+rctvjEHssioomwLxrrCt7H9hFSwVjeYT7UD81Mj0CQ9x4eTwWFNJAyAjec6bA
            y99zw8tyIVe2RyEHYBEyZjO8+yAhmp1y1gGxlj6ChhI3yY0rPbLOTT2xFnCRdpLS
            5gF+H5BZF0d5yDegF5OBlOtc7u5pDgr1Ujv+sdvmcIrlaKOn5WGtf2akuffD++kw
            Vkkg9r9s7u8rhD7539shKs3kWORY8bpGHL+nmdNp9FPdvuJxcGQAAA==
            =KBMh
            -----END PGP MESSAGE-----
          fp: 4BFE628FFB40778D5A0C173F84BFA7FAFB671574
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
