---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-external-hdd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: external-hdd
  resources:
    requests:
      storage: 128Mi
