---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-external
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: external-hdd
  resources:
    requests:
      storage: 50Gi
