apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-hdd
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/expansion1/local"
