kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: syncthing-data
  annotations:
    nfs.io/storage-path: "syncthing-data" # not required, depending on whether this annotation was shown in the storage class description
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
