---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-local-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: external-hdd
  resources:
    requests:
      storage: 50Gi
