---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-local-hdd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: local-pv
  resources:
    requests:
      storage: 128Mi
